### ISSUE TITLE
START FEATURE EXTRACTION出现错误

### ISSUE THREAD

**Issue by Tonytom66** [ttengwang/PDVC#10]
作者您好，我运行您的代码之后，在START FEATURE EXTRACTION阶段出现RuntimeError: CUDA error: unknown error，其它地方均无错误，请问我该如何解决它？
![image](https://user-images.githubusercontent.com/50938317/144397629-66a00b3c-c6d3-4a5f-9ece-741e737a586d.png)
![image](https://user-images.githubusercontent.com/50938317/144397698-32ec1c93-0fac-4494-863b-57f35bfb4014.png)

**Comment by ttengwang** [comment]
我未遇到这种错误，需要更详细说明下环境：显卡，CUDA, python, pytorch 版本

**Comment by Tonytom66** [comment]
> 我未遇到这种错误，需要更详细说明下环境：显卡，CUDA, python, pytorch 版本
显卡：NVIDIA GeForce GTX 1050
CUDA Version 10.1.243
Python3.7
pytorch1.71
![image](https://user-images.githubusercontent.com/50938317/144413877-9a0f263f-7692-447c-b02f-c874930cfd0d.png)

**Comment by ttengwang** [comment]
> > 我未遇到这种错误，需要更详细说明下环境：显卡，CUDA, python, pytorch 版本
> > 显卡：NVIDIA GeForce GTX 1050
> > CUDA Version 10.1.243
> > Python3.7
> > pytorch1.71
> > ![image](https://user-images.githubusercontent.com/50938317/144413877-9a0f263f-7692-447c-b02f-c874930cfd0d.png)

@Tonytom66 谢谢，应该是1050显存只有2GB，显存不够。参考https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/59

**Comment by ttengwang** [comment]
@Tonytom66 请尝试在python video_backbone/TSP/extract_features/extract_features.py 指令后面多加一个参数 --batch-size 这里batch size默认为32，减小batch size后应该可以解决此问题。

**Comment by Tonytom66** [comment]
@ttengwang 这确实解决了我的问题，非常感谢！！！
